export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const REGISTER_LOADING = 'REGISTER_LOADING'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const GET_USER_LOADING = 'GET_USER_LOADING'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'

export const GET_FLIGHTS_LOADING = 'GET_FLIGHTS_LOADING'
export const GET_FLIGHTS_SUCCESS = 'GET_FLIGHTS_SUCCESS'
export const GET_FLIGHTS_ERROR = 'GET_FLIGHTS_ERROR'

export const RESET_DIALOG = 'RESET_DIALOG'
